### ISSUE TITLE
moment from not working

### ISSUE THREAD

**Issue by mocheaz** [brockpetrie/vue-moment#1]
I have a line like this:
```
<small class="text-muted">{{comment.created_at | moment from true}}</small>
```
While 'comment.created_at' is mysql datetime formatted date.
But i'm getting Uncaught TypeError: Cannot read property 'replace' of undefined.

Any idea why?

'moment calendar' is the same but 'moment "dddd, MMMM Do YYYY, h:mm:ss a"' is working good.

**Comment by brockpetrie** [comment]
That's odd! Can you give me the line number for the error? Is it coming from moment.js or vue-moment.js?

**Comment by mocheaz** [comment]
that's the line: 	
```
return a.replace(/^("|')|("|')$/g, "");
```
I'm using the minified file. I think it's line 4

Here it
```
Vue.filter("moment", function() {
	function d() {
		var a = Array.prototype.slice.call(arguments).map(function(a) {
			return a.replace(/^("|')|("|')$/g, "")
		}
		)
```

**Comment by mocheaz** [comment]
Do you need more code from my page?

**Comment by brockpetrie** [comment]
I took a look, and it appears that Vue has changed how it passes arguments to filters. This is caused a whole lot of problems, but fortunately the fix for your use case should be pretty simple:

`<small class="text-muted">{{comment.created_at | moment "from" "true"}}</small>`

Basically, wrap your filter arguments in quotes.

I'll try to update the library and docs in the coming weeks.

**Comment by mocheaz** [comment]
Great.
It worked.

**Comment by matthiasweiss** [comment]
Thanks for the solution to this problem, I was thinking that the problem was on the side of Vue :)

**Comment by brockpetrie** [comment]
Glad it helped! Reopening this so people are more likely to see it.

**Comment by Theodosis** [comment]
Could you make sure to update the readme to include this? Took me a while to figure it out...
