### ISSUE TITLE
Deprecation warning: moment construction falls back to js Date

### ISSUE THREAD

**Issue by lukpep** [brockpetrie/vue-moment#7]
> Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
> Arguments: [object Object]
> Error
>     at Function.createFromInputFallback (http://localhost:8080/build/build.js:46871:106)
>     at configFromString (http://localhost:8080/build/build.js:47769:33)
>     at configFromInput (http://localhost:8080/build/build.js:48275:14)
>     at prepareConfig (http://localhost:8080/build/build.js:48258:14)
>     at createFromConfig (http://localhost:8080/build/build.js:48225:45)
>     at createLocalOrUTC (http://localhost:8080/build/build.js:48307:17)
>     at local__createLocal (http://localhost:8080/build/build.js:48311:17)
>     at utils_hooks__hooks (http://localhost:8080/build/build.js:46616:30)
>     at VueComponent.<anonymous> (http://localhost:8080/build/build.js:46493:13)
>     at VueComponent.Vue._applyFilters (http://localhost:8080/build/build.js:17001:19)

warn from moment.js.
vue-moment probably needs to change constructor for original moment.js objects

**Comment by brockpetrie** [comment]
This quick fix would be to use an older version of moment for now. Will try to unpack the actual problem today.

**Comment by BrockReece** [comment]
One of the main reasons for my last pull request is that my colleague was having problems with juggling multiple versions of moment that I think is referenced in the link below.

https://github.com/moment/moment/issues/3124

So I think enforcing an earlier version of moment would cause knock on problems elsewhere.

**Comment by brockpetrie** [comment]
@lukpep can you paste your input?

**Comment by brockpetrie** [comment]
Never mind, not really a problem here. Historically, moment has used `new Date()` when creating a date object from a string input. Since that's unreliable (see moment/moment#1407) they are just removing that fallback altogether and now just expect either a Date object, or a valid ISO formatted date string. The way to squelch this error is to either:

1. Pass a valid ISO date string (e.g. `2016-01-01T09:30:00`)
2. Pass your non-ISO string as a new Date object (e.g. `{{ new Date(myDate) | moment 'MMMM Do YYYY' }}`)

In the next major release (2.0.0), I'll add a method for passing moment a date pattern for parsing the input (e.g. something like accepting an additional format string in the args `{{ myDate | moment 'YYYY MM DD' 'MMMM Do YYYY' }}`).
